"""
Wraps your real src/suggestions/suggestion_engine.py — same principle
as cli.py: import your actual logic, don't reimplement it.
"""
import sys
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent.parent  # burnout-project root
SRC_DIR = BASE_DIR / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

from suggestions.suggestion_engine import get_suggestions as _get_suggestions


def get_suggestions_for_session(
    cli: float,
    typing_mean: float,
    typing_variance: float,
    task_switching: float,
    work_duration: float,
    late_night: int,
) -> list[str]:
    """
    Returns plain strings for the mobile app, generated by your real
    suggestion engine.
    """
    suggestions = _get_suggestions(
        cli=cli,
        typing_mean=typing_mean,
        typing_variance=typing_variance,
        task_switching=task_switching,
        work_duration=work_duration,
        late_night=late_night,
    )
    return [f"{s.icon} {s.title}: {s.message}" for s in suggestions]